included:
  - MyBlogDemo
excluded:
  - Pods
analyzer_rules:
  - unused_private_declaration
disabled_rules:
  - private_unit_test
  - redundant_string_enum_value
  - shorthand_operator
  - superfluous_disable_command
  - type_body_length
  - xctfail_message
  - block_based_kvo
  - closure_body_length
  - file_header
  - file_length
  - file_name
  - file_types_order
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - multiline_arguments
  - unowned_variable_capture
  - type_contents_order
  - cyclomatic_complexity
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - last_where
  - first_where
  - implicit_return
  - joined_default_parameter
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - prefixed_toplevel_constant
  - switch_case_on_newline
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces